version: '3.7'

networks:
  cronsun:
    name: cronsun
    driver: bridge
    ipam:
      config:
        - subnet: "10.128.0.0/16"

volumes:
  etcd-node1:
  etcd-node2:
  etcd-node3:
  mongo-data:
  ssl-certs:

services:
  etcd-node1:
    image: quay.io/coreos/etcd:latest
    container_name: cronsun_etcd_node1
    command: /usr/local/bin/etcd --data-dir=/etcd-data --name etcd-node1 --advertise-client-urls http://10.128.0.2:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://10.128.0.2:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster-cronsun --initial-cluster etcd-node1=http://10.128.0.2:2380,etcd-node2=http://10.128.0.3:2380,etcd-node3=http://10.128.0.4:2380 --initial-cluster-state new
    volumes:
      - etcd-node1:/etcd-data:rw
    networks:
      cronsun:
        ipv4_address: "10.128.0.2"

  etcd-node2:
    image: quay.io/coreos/etcd:latest
    container_name: cronsun_etcd_node2
    command: /usr/local/bin/etcd --data-dir=/etcd-data --name etcd-node2 --advertise-client-urls http://10.128.0.3:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://10.128.0.3:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster-cronsun --initial-cluster etcd-node1=http://10.128.0.2:2380,etcd-node2=http://10.128.0.3:2380,etcd-node3=http://10.128.0.4:2380 --initial-cluster-state new
    volumes:
      - etcd-node2:/etcd-data:rw
    networks:
      cronsun:
        ipv4_address: "10.128.0.3"

  etcd-node3:
    image: quay.io/coreos/etcd:latest
    container_name: cronsun_etcd_node3
    command: /usr/local/bin/etcd --data-dir=/etcd-data --name etcd-node3 --advertise-client-urls http://10.128.0.4:2379 --listen-client-urls http://0.0.0.0:2379 --initial-advertise-peer-urls http://10.128.0.4:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster-token etcd-cluster-cronsun --initial-cluster etcd-node1=http://10.128.0.2:2380,etcd-node2=http://10.128.0.3:2380,etcd-node3=http://10.128.0.4:2380 --initial-cluster-state new
    volumes:
      - etcd-node3:/etcd-data:rw
    networks:
      cronsun:
        ipv4_address: "10.128.0.4"

  mongo:
    image: mongo:3.4-xenial
    container_name: cronsun_mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo-data:/data/db:rw
    networks:
      cronsun:
        ipv4_address: "10.128.0.40"

  worker-php56:
    image: dascencio/cronsun-worker-php:5.6-fpm-alpine
    container_name: cronsun_worker_php56
    volumes:
      - ${CRONSUN_CONFIG}:/opt/cronsun/conf:ro
    networks:
      cronsun:
        ipv4_address: "10.128.0.10"
    depends_on:
      - web

  web:
    image: dascencio/cronsun-web:0.3.5
    container_name: cronsun_web
    volumes:
      - ${CRONSUN_CONFIG}:/opt/cronsun/conf:ro
    networks:
      cronsun:
        ipv4_address: "10.128.0.20"
    depends_on:
      - etcd-node1
      - etcd-node2
      - etcd-node3
      - mongo
    labels:
      - traefik.enable=true
      - traefik.http.routers.cronsun-web.rule=${CRONSUN_DOMAINS}
      - traefik.http.routers.cronsun-web.middlewares=cronsun-auth,cronsun-ratelimit
      - traefik.http.middlewares.cronsun-auth.digestauth.users=${INGRESS_ADMIN_USER}
      - traefik.http.middlewares.cronsun-auth.digestauth.realm=${INGRESS_REALM_USER}
      - traefik.http.middlewares.cronsun-auth.digestauth.removeheader=true
      - traefik.http.middlewares.cronsun-ratelimit.ratelimit.average=50
      - traefik.http.middlewares.cronsun-ratelimit.ratelimit.burst=50

  ingress:
    image: traefik:v2.1
    container_name: cronsun_ingress
    command:
      - --log.level=DEBUG
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      #- --certificatesResolvers.sample.acme.email=${INGRESS_ADMIN_MAIL}
      #- --certificatesResolvers.sample.acme.storage=/acme/certificates.json
      #- --certificatesResolvers.sample.acme.httpChallenge.entryPoint=web
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ssl-certs:/acme:rw
    networks:
      cronsun:
        ipv4_address: "10.128.0.100"
    ports:
      - ${INGRESS_HTTP_PORT}:80
      - ${INGRESS_HTTPS_PORT}:443
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=${INGRESS_DOMAINS}"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=admin-auth,ingress-ratelimit"
      - "traefik.http.middlewares.admin-auth.digestauth.users=${INGRESS_ADMIN_USER}"
      - "traefik.http.middlewares.admin-auth.digestauth.realm=${INGRESS_REALM_USER}"
      - "traefik.http.middlewares.admin-auth.digestauth.removeheader=true"
      - "traefik.http.middlewares.ingress-ratelimit.ratelimit.average=20"
      - "traefik.http.middlewares.ingress-ratelimit.ratelimit.burst=10"